name: DOCR Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: DOCR Login
        uses: docker/login-action@v2.2.0
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build
        run: DOCKER_BUILDKIT=1 docker build -f Dockerfile -t ekko-dot-dev .
      - name: Tag
        run: docker tag eko-dot-dev registry.digitalocean.com/${{ vars.DOCR_NAME }}/ekko-dot-dev
      - name: Push
        run: docker push registry.digitalocean.com/${{ vars.DOCR_NAME }}/ekko-dot-dev
